In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('us-cities-wikipedia.csv', delimiter=',')

In [14]:
df.head(25)

,2016 rank,City,State[5],2016 estimate,2010 Census,Change,2016 land area (english),2016 land area (metric),2016 population density (english),2016 population density (metric),Location
0,1,New York[6],New York,"8,537,673","8,175,133",+4.43%,301.5 sq mi,780.9 km2,"28,317/sq mi","10,933/km2",40°39′49″N 73°56′19″W﻿ / ﻿40.6635°N 73.9387°W
1,2,Los Angeles,California,"3,976,322","3,792,621",+4.84%,468.7 sq mi,"1,213.9 km2","8,484/sq mi","3,276/km2",34°01′10″N 118°24′39″W﻿ / ﻿34.0194°N 118.4108°W
2,3,Chicago,Illinois,"2,704,958","2,695,598",+0.35%,227.3 sq mi,588.7 km2,"11,900/sq mi","4,600/km2",41°50′15″N 87°40′54″W﻿ / ﻿41.8376°N 87.6818°W
3,4,Houston[7],Texas,"2,303,482","2,100,263",+9.68%,637.5 sq mi,"1,651.1 km2","3,613/sq mi","1,395/km2",29°47′12″N 95°23′27″W﻿ / ﻿29.7866°N 95.3909°W
4,5,Phoenix,Arizona,"1,615,017","1,445,632",+11.72%,517.6 sq mi,"1,340.6 km2","3,120/sq mi","1,200/km2",33°34′20″N 112°05′24″W﻿ / ﻿33.5722°N 112.0901°W
5,6,Philadelphia[8],Pennsylvania,"1,567,872","1,526,006",+2.74%,134.2 sq mi,347.6 km2,"11,683/sq mi","4,511/km2",40°00′34″N 75°08′00″W﻿ / ﻿40.0094°N 75.1333°W
6,7,San Antonio,Texas,"1,492,510","1,327,407",+12.44%,461.0 sq mi,"1,194.0 km2","3,238/sq mi","1,250/km2",29°28′21″N 98°31′30″W﻿ / ﻿29.4724°N 98.5251°W
7,8,San Diego,California,"1,406,630","1,307,402",+7.59%,325.2 sq mi,842.3 km2,"4,325/sq mi","1,670/km2",32°48′55″N 117°08′06″W﻿ / ﻿32.8153°N 117.1350°W
8,9,Dallas,Texas,"1,317,929","1,197,816",+10.03%,340.9 sq mi,882.9 km2,"3,866/sq mi","1,493/km2",32°47′36″N 96°45′59″W﻿ / ﻿32.7933°N 96.7665°W
9,10,San Jose,California,"1,025,350","945,942",+8.39%,177.5 sq mi,459.7 km2,"5,777/sq mi","2,231/km2",37°17′48″N 121°49′08″W﻿ / ﻿37.2967°N 121.8189°W
10,11,Austin,Texas,"947,890","790,390",+19.93%,312.7 sq mi,809.9 km2,"3,031/sq mi","1,170/km2",30°18′14″N 97°45′16″W﻿ / ﻿30.3039°N 97.7544°W
11,12,Jacksonville[9],Florida,"880,619","821,784",+7.16%,747.4 sq mi,"1,935.8 km2","1,178/sq mi",455/km2,30°20′13″N 81°39′42″W﻿ / ﻿30.3369°N 81.6616°W
12,13,San Francisco[10],California,"870,887","805,235",+8.15%,46.9 sq mi,121.5 km2,"18,569/sq mi","7,170/km2",37°43′38″N 123°01′56″W﻿ / ﻿37.7272°N 123.0322°W
13,14,Columbus,Ohio,"860,090","787,033",+9.28%,218.5 sq mi,565.9 km2,"3,936/sq mi","1,520/km2",39°59′07″N 82°59′05″W﻿ / ﻿39.9852°N 82.9848°W
14,15,Indianapolis[11],Indiana,"855,164","820,445",+4.23%,361.5 sq mi,936.3 km2,"2,366/sq mi",914/km2,39°46′36″N 86°08′45″W﻿ / ﻿39.7767°N 86.1459°W
15,16,Fort Worth,Texas,"854,113","741,206",+15.23%,342.9 sq mi,888.1 km2,"2,491/sq mi",962/km2,32°46′53″N 97°20′48″W﻿ / ﻿32.7815°N 97.3467°W
16,17,Charlotte,North Carolina,"842,051","731,424",+15.12%,305.4 sq mi,791.0 km2,"2,757/sq mi","1,064/km2",35°12′28″N 80°49′52″W﻿ / ﻿35.2078°N 80.8310°W
17,18,Seattle,Washington,"704,352","608,660",+15.72%,83.8 sq mi,217.0 km2,"8,405/sq mi","3,245/km2",47°37′14″N 122°21′03″W﻿ / ﻿47.6205°N 122.3509°W
18,19,Denver[12],Colorado,"693,060","600,158",+15.48%,153.3 sq mi,397.0 km2,"4,521/sq mi","1,746/km2",39°45′43″N 104°52′52″W﻿ / ﻿39.7619°N 104.8811°W
19,20,El Paso,Texas,"683,080","649,121",+5.23%,256.8 sq mi,665.1 km2,"2,660/sq mi","1,030/km2",31°50′54″N 106°25′37″W﻿ / ﻿31.8484°N 106.4270°W
20,21,Washington[13],District of Columbia,"681,170","601,723",+13.20%,61.1 sq mi,158.2 km2,"11,148/sq mi","4,304/km2",38°54′15″N 77°01′02″W﻿ / ﻿38.9041°N 77.0172°W
21,22,Boston,Massachusetts,"673,184","617,594",+9.00%,48.3 sq mi,125.1 km2,"13,938/sq mi","5,381/km2",42°19′55″N 71°01′13″W﻿ / ﻿42.3320°N 71.0202°W
22,23,Detroit,Michigan,"672,795","713,777",−5.74%,138.8 sq mi,359.5 km2,"4,847/sq mi","1,871/km2",42°22′59″N 83°06′08″W﻿ / ﻿42.3830°N 83.1022°W
23,24,Nashville[14],Tennessee,"660,388","601,222",+9.84%,475.9 sq mi,"1,232.6 km2","1,388/sq mi",536/km2,36°10′18″N 86°47′06″W﻿ / ﻿36.1718°N 86.7850°W
24,25,Memphis,Tennessee,"652,717","646,889",+0.90%,317.4 sq mi,822.1 km2,"2,056/sq mi",794/km2,35°06′10″N 89°58′39″W﻿ / ﻿35.1028°N 89.9774°W